# Funding platforms for SolShield
# These links will be shown in the "Sponsor" button on GitHub

github: [oh-ashen-one]
# ko_fi: solshield
# open_collective: solshield
# custom: ["https://solshield.dev/donate"]
