/**
 * SolShield Patterns Batch 53 - Sec3 2025 Enhanced + Latest Exploits
 * 
 * 70 patterns covering:
 * - Business Logic Deep Patterns (38.5% of all Solana vulns)
 * - Input Validation Advanced (25%)
 * - Access Control Edge Cases (19%)
 * - 2024-2025 Emerging Attack Vectors
 * 
 * Based on: Sec3 2025 Security Review (163 audits, 1,669 vulns)
 * IDs: SOL2001-SOL2070
 */

import type { PatternInput, Finding } from './index.js';

function findLine(content: string, idx: number): number {
  return content.substring(0, idx).split('\n').length;
}

function getSnippet(content: string, line: number): string {
  const lines = content.split('\n');
  const start = Math.max(0, line - 2);
  const end = Math.min(lines.length, line + 2);
  return lines.slice(start, end).join('\n').substring(0, 200);
}

export function checkBatch53Patterns(input: PatternInput): Finding[] {
  const findings: Finding[] = [];
  const content = input.rust?.content || '';
  const path = input.path;
  if (!content) return findings;

  const patterns: Array<{
    id: string;
    name: string;
    severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
    regex: RegExp;
    desc: string;
    rec: string;
  }> = [
    // Business Logic Deep Patterns (SOL2001-SOL2020)
    { id: 'SOL2001', name: 'State Machine Skip', severity: 'critical',
      regex: /state[\s\S]{0,30}transition[\s\S]{0,50}(?![\s\S]{0,30}require|[\s\S]{0,30}assert)/i,
      desc: 'State transitions without validation allow skipping required states.',
      rec: 'Validate current state before allowing transition to next state.' },
    { id: 'SOL2002', name: 'Deadline Bypass', severity: 'high',
      regex: /deadline|expiry|expire[\s\S]{0,50}(?:clock|timestamp)[\s\S]{0,30}(?![\s\S]{0,20}>=|[\s\S]{0,20}<=)/i,
      desc: 'Deadline comparisons may allow edge-case bypasses.',
      rec: 'Use strict comparisons and check both upper and lower bounds.' },
    { id: 'SOL2003', name: 'Fee Calculation Precision Loss', severity: 'high',
      regex: /fee[\s\S]{0,30}(?:\*|multiply)[\s\S]{0,30}(?:\/|divide)(?![\s\S]{0,20}checked)/i,
      desc: 'Fee calculations may lose precision due to operation order.',
      rec: 'Multiply before dividing to preserve precision.' },
    { id: 'SOL2004', name: 'Reward Accumulation Drift', severity: 'high',
      regex: /reward[\s\S]{0,30}(?:accumulate|accrue|earn)[\s\S]{0,50}(?:per_share|rate)/i,
      desc: 'Reward accumulation may drift from expected values over time.',
      rec: 'Use high-precision fixed-point math for reward calculations.' },
    { id: 'SOL2005', name: 'Partial Fill Edge Case', severity: 'medium',
      regex: /partial[\s\S]{0,20}(?:fill|execute)[\s\S]{0,50}(?:amount|quantity)[\s\S]{0,20}(?![\s\S]{0,15}min)/i,
      desc: 'Partial fills without minimum amounts enable dust attacks.',
      rec: 'Enforce minimum fill amounts to prevent dust exploitation.' },
    { id: 'SOL2006', name: 'Slippage Off-by-One', severity: 'medium',
      regex: /slippage[\s\S]{0,30}(?:>|<)[\s\S]{0,20}(?![\s\S]{0,10}=)/i,
      desc: 'Slippage checks using strict comparison may miss boundary.',
      rec: 'Use >= or <= for slippage comparisons.' },
    { id: 'SOL2007', name: 'Cooldown Reset Exploit', severity: 'high',
      regex: /cooldown[\s\S]{0,30}(?:set|update|reset)[\s\S]{0,50}(?![\s\S]{0,30}require|[\s\S]{0,30}assert)/i,
      desc: 'Cooldowns can be reset without proper validation.',
      rec: 'Verify cooldown has expired before allowing reset.' },
    { id: 'SOL2008', name: 'Epoch Boundary Race', severity: 'high',
      regex: /epoch[\s\S]{0,30}(?:boundary|transition|change)[\s\S]{0,50}(?:stake|unstake|claim)/i,
      desc: 'Operations at epoch boundaries may have race conditions.',
      rec: 'Add explicit epoch boundary checks and handle transitions safely.' },
    { id: 'SOL2009', name: 'Liquidation Cascade', severity: 'critical',
      regex: /liquidat[\s\S]{0,30}(?:loop|iterate|batch)[\s\S]{0,50}(?![\s\S]{0,30}limit)/i,
      desc: 'Batch liquidations without limits can cascade failures.',
      rec: 'Limit liquidations per transaction and add circuit breakers.' },
    { id: 'SOL2010', name: 'Position Close During Settle', severity: 'high',
      regex: /close[\s\S]{0,30}position[\s\S]{0,50}settl[\s\S]{0,30}(?![\s\S]{0,20}lock|[\s\S]{0,20}pending)/i,
      desc: 'Positions closed during settlement can lose funds.',
      rec: 'Lock positions during settlement period.' },
    { id: 'SOL2011', name: 'Vault Share Inflation', severity: 'critical',
      regex: /share[\s\S]{0,30}(?:mint|issue)[\s\S]{0,50}(?:deposit|balance)[\s\S]{0,30}(?![\s\S]{0,20}total)/i,
      desc: 'Share minting without checking total supply enables inflation.',
      rec: 'Always calculate shares relative to total supply.' },
    { id: 'SOL2012', name: 'First Depositor Attack', severity: 'critical',
      regex: /(?:first|initial)[\s\S]{0,20}deposit[\s\S]{0,50}(?![\s\S]{0,30}minimum|[\s\S]{0,30}seed)/i,
      desc: 'First depositor can manipulate share price.',
      rec: 'Require minimum initial deposit or seed the vault.' },
    { id: 'SOL2013', name: 'Withdrawal Queue Jump', severity: 'high',
      regex: /withdrawal[\s\S]{0,30}queue[\s\S]{0,50}(?:process|execute)[\s\S]{0,30}(?![\s\S]{0,20}fifo|[\s\S]{0,20}order)/i,
      desc: 'Withdrawal queue can be bypassed without proper ordering.',
      rec: 'Enforce FIFO ordering for withdrawal queues.' },
    { id: 'SOL2014', name: 'Interest Compounding Gap', severity: 'medium',
      regex: /interest[\s\S]{0,30}compound[\s\S]{0,50}(?![\s\S]{0,30}continuous|[\s\S]{0,30}per_second)/i,
      desc: 'Interest compounding gaps allow timing exploitation.',
      rec: 'Use continuous compounding or per-second accrual.' },
    { id: 'SOL2015', name: 'Collateral Ratio Manipulation', severity: 'critical',
      regex: /collateral[\s\S]{0,30}ratio[\s\S]{0,50}(?:flash|instant|atomic)/i,
      desc: 'Collateral ratios can be manipulated in single transaction.',
      rec: 'Use TWAP or delayed price for collateral calculations.' },
    { id: 'SOL2016', name: 'Referral Fee Bypass', severity: 'medium',
      regex: /referr[\s\S]{0,30}fee[\s\S]{0,50}(?:self|same)[\s\S]{0,20}(?![\s\S]{0,15}block|[\s\S]{0,15}prevent)/i,
      desc: 'Users can refer themselves to capture referral fees.',
      rec: 'Prevent self-referral by checking account relationships.' },
    { id: 'SOL2017', name: 'Auction Sniping', severity: 'high',
      regex: /auction[\s\S]{0,30}(?:end|close|finish)[\s\S]{0,50}(?![\s\S]{0,30}extension|[\s\S]{0,30}anti_snipe)/i,
      desc: 'Auctions without extension mechanism enable sniping.',
      rec: 'Add bid extension period to prevent last-second sniping.' },
    { id: 'SOL2018', name: 'Vote Power Flash', severity: 'critical',
      regex: /vote[\s\S]{0,30}(?:power|weight)[\s\S]{0,50}(?:balance|token)[\s\S]{0,30}(?![\s\S]{0,20}snapshot)/i,
      desc: 'Vote power from current balance enables flash loan governance.',
      rec: 'Use historical snapshots for voting power.' },
    { id: 'SOL2019', name: 'Pool Imbalance Exploit', severity: 'high',
      regex: /pool[\s\S]{0,30}(?:imbalance|ratio)[\s\S]{0,50}(?:swap|trade)[\s\S]{0,30}(?![\s\S]{0,20}limit)/i,
      desc: 'Extreme pool imbalances can be exploited for profit.',
      rec: 'Add imbalance limits and circuit breakers.' },
    { id: 'SOL2020', name: 'Margin Call Timing', severity: 'high',
      regex: /margin[\s\S]{0,30}call[\s\S]{0,50}(?:timestamp|clock)[\s\S]{0,30}(?![\s\S]{0,20}grace|[\s\S]{0,20}window)/i,
      desc: 'Margin calls without grace period cause unfair liquidations.',
      rec: 'Add grace period for margin calls.' },

    // Input Validation Advanced (SOL2021-SOL2040)
    { id: 'SOL2021', name: 'Pubkey Zero Check', severity: 'critical',
      regex: /pubkey[\s\S]{0,30}(?:=|==)[\s\S]{0,30}(?![\s\S]{0,20}system_program|[\s\S]{0,20}Pubkey::default)/i,
      desc: 'Pubkey comparison without zero/default check.',
      rec: 'Check for Pubkey::default() before comparisons.' },
    { id: 'SOL2022', name: 'String Length DoS', severity: 'high',
      regex: /String[\s\S]{0,30}(?:len|length)[\s\S]{0,30}(?![\s\S]{0,20}<|[\s\S]{0,20}<=|[\s\S]{0,20}max)/i,
      desc: 'Unbounded string length enables DoS attacks.',
      rec: 'Enforce maximum string length limits.' },
    { id: 'SOL2023', name: 'Array Index Bounds', severity: 'critical',
      regex: /\[[\s\S]{0,20}(?:index|idx|i)[\s\S]{0,10}\][\s\S]{0,30}(?![\s\S]{0,20}get\(|[\s\S]{0,20}bounds)/i,
      desc: 'Array access without bounds checking.',
      rec: 'Use .get() for safe array access.' },
    { id: 'SOL2024', name: 'Decimal Truncation', severity: 'high',
      regex: /as\s+u(?:8|16|32|64)[\s\S]{0,20}(?:decimal|price|amount)/i,
      desc: 'Casting to smaller int truncates decimal precision.',
      rec: 'Use appropriate integer sizes for decimal values.' },
    { id: 'SOL2025', name: 'Negative Amount Cast', severity: 'critical',
      regex: /as\s+i(?:8|16|32|64)[\s\S]{0,30}(?:amount|balance|quantity)/i,
      desc: 'Casting unsigned to signed may produce negative values.',
      rec: 'Validate values before casting to signed types.' },
    { id: 'SOL2026', name: 'Timestamp Future Check', severity: 'medium',
      regex: /timestamp[\s\S]{0,30}(?:>|>=)[\s\S]{0,30}clock[\s\S]{0,20}(?![\s\S]{0,15}<|[\s\S]{0,15}future)/i,
      desc: 'Timestamp validation missing future check.',
      rec: 'Reject timestamps too far in the future.' },
    { id: 'SOL2027', name: 'Slot Overflow Risk', severity: 'high',
      regex: /slot[\s\S]{0,30}(?:\+|add)[\s\S]{0,30}(?![\s\S]{0,20}checked|[\s\S]{0,20}saturating)/i,
      desc: 'Slot arithmetic may overflow at high values.',
      rec: 'Use checked arithmetic for slot calculations.' },
    { id: 'SOL2028', name: 'Lamport Dust', severity: 'low',
      regex: /lamports[\s\S]{0,30}(?:<|<=)[\s\S]{0,20}(?:1000|100|10|1)[\s\S]{0,10}(?![\s\S]{0,10}0)/i,
      desc: 'Operations on dust lamport amounts waste compute.',
      rec: 'Enforce minimum lamport thresholds.' },
    { id: 'SOL2029', name: 'Base58 Decode Unchecked', severity: 'medium',
      regex: /base58[\s\S]{0,30}decode[\s\S]{0,30}(?:unwrap|expect)/i,
      desc: 'Base58 decode failure not properly handled.',
      rec: 'Handle base58 decode errors gracefully.' },
    { id: 'SOL2030', name: 'Instruction Data Size', severity: 'high',
      regex: /instruction[\s\S]{0,30}data[\s\S]{0,50}(?:len|length)[\s\S]{0,20}(?![\s\S]{0,15}>=|[\s\S]{0,15}require)/i,
      desc: 'Instruction data size not validated.',
      rec: 'Validate instruction data length before parsing.' },
    { id: 'SOL2031', name: 'Remaining Accounts Unbounded', severity: 'high',
      regex: /remaining_accounts[\s\S]{0,50}(?:iter|for_each)[\s\S]{0,30}(?![\s\S]{0,20}take\(|[\s\S]{0,20}limit)/i,
      desc: 'Remaining accounts iteration unbounded.',
      rec: 'Limit remaining accounts iteration count.' },
    { id: 'SOL2032', name: 'Seeds Length Validation', severity: 'high',
      regex: /seeds[\s\S]{0,30}(?:len|length)[\s\S]{0,30}(?![\s\S]{0,20}<=\s*32|[\s\S]{0,20}MAX_SEED)/i,
      desc: 'PDA seed length not validated against max.',
      rec: 'Validate seed lengths <= 32 bytes each.' },
    { id: 'SOL2033', name: 'Memo Injection', severity: 'medium',
      regex: /memo[\s\S]{0,30}(?:data|content|message)[\s\S]{0,30}(?![\s\S]{0,20}sanitize|[\s\S]{0,20}escape)/i,
      desc: 'Memo content not sanitized for display.',
      rec: 'Sanitize memo content before display/logging.' },
    { id: 'SOL2034', name: 'URL Validation', severity: 'medium',
      regex: /url|uri[\s\S]{0,30}(?:http|https)[\s\S]{0,30}(?![\s\S]{0,20}validate|[\s\S]{0,20}whitelist)/i,
      desc: 'URLs stored without validation.',
      rec: 'Validate URLs against allowed protocols and domains.' },
    { id: 'SOL2035', name: 'Bitmap Overflow', severity: 'high',
      regex: /bitmap|bitset[\s\S]{0,30}(?:set|get|toggle)[\s\S]{0,30}(?![\s\S]{0,20}bounds|[\s\S]{0,20}<\s*\d)/i,
      desc: 'Bitmap operations without bounds checking.',
      rec: 'Validate bit index before bitmap operations.' },
    { id: 'SOL2036', name: 'Enum Discriminant Check', severity: 'high',
      regex: /enum[\s\S]{0,50}(?:from_u8|from_byte)[\s\S]{0,30}(?![\s\S]{0,20}match|[\s\S]{0,20}try)/i,
      desc: 'Enum deserialization without discriminant validation.',
      rec: 'Use try_from or match for enum deserialization.' },
    { id: 'SOL2037', name: 'Float Precision', severity: 'high',
      regex: /f32|f64[\s\S]{0,30}(?:price|amount|balance)/i,
      desc: 'Floating point used for financial calculations.',
      rec: 'Use fixed-point decimals for financial values.' },
    { id: 'SOL2038', name: 'Hash Preimage', severity: 'medium',
      regex: /hash[\s\S]{0,30}(?:preimage|reveal)[\s\S]{0,30}(?![\s\S]{0,20}commit|[\s\S]{0,20}timelock)/i,
      desc: 'Hash reveal without commit-reveal scheme.',
      rec: 'Use commit-reveal pattern for hash-based operations.' },
    { id: 'SOL2039', name: 'Nonce Replay', severity: 'critical',
      regex: /nonce[\s\S]{0,30}(?:use|consume)[\s\S]{0,30}(?![\s\S]{0,20}increment|[\s\S]{0,20}invalidate)/i,
      desc: 'Nonce not invalidated after use.',
      rec: 'Increment or invalidate nonces after each use.' },
    { id: 'SOL2040', name: 'Version Compatibility', severity: 'medium',
      regex: /version[\s\S]{0,30}(?:check|compare)[\s\S]{0,30}(?![\s\S]{0,20}>=|[\s\S]{0,20}compatible)/i,
      desc: 'Version checking may miss compatibility issues.',
      rec: 'Implement proper semantic version compatibility.' },

    // Access Control Edge Cases (SOL2041-SOL2055)
    { id: 'SOL2041', name: 'Authority Downgrade', severity: 'critical',
      regex: /authority[\s\S]{0,30}(?:downgrade|reduce|lower)[\s\S]{0,30}(?![\s\S]{0,20}require|[\s\S]{0,20}verify)/i,
      desc: 'Authority can be downgraded without proper checks.',
      rec: 'Require current authority signature for downgrades.' },
    { id: 'SOL2042', name: 'Freeze Authority Transfer', severity: 'high',
      regex: /freeze[\s\S]{0,30}authority[\s\S]{0,30}transfer[\s\S]{0,30}(?![\s\S]{0,20}verify|[\s\S]{0,20}require)/i,
      desc: 'Freeze authority can be transferred unsafely.',
      rec: 'Implement two-step freeze authority transfer.' },
    { id: 'SOL2043', name: 'Delegate Scope Creep', severity: 'high',
      regex: /delegate[\s\S]{0,30}(?:amount|scope|permission)[\s\S]{0,30}(?:update|increase)/i,
      desc: 'Delegate permissions can be expanded without limit.',
      rec: 'Cap delegate permissions at initial grant level.' },
    { id: 'SOL2044', name: 'Emergency Admin Abuse', severity: 'critical',
      regex: /emergency[\s\S]{0,30}admin[\s\S]{0,50}(?:drain|withdraw|transfer)[\s\S]{0,30}(?![\s\S]{0,20}timelock)/i,
      desc: 'Emergency admin can drain without timelock.',
      rec: 'Add timelock even for emergency operations.' },
    { id: 'SOL2045', name: 'Pause Without Unpause', severity: 'high',
      regex: /pause[\s\S]{0,50}(?![\s\S]{0,50}unpause|[\s\S]{0,50}resume)/i,
      desc: 'Pause mechanism without corresponding unpause.',
      rec: 'Implement unpause with appropriate controls.' },
    { id: 'SOL2046', name: 'Role Hierarchy Bypass', severity: 'high',
      regex: /role[\s\S]{0,30}(?:check|verify)[\s\S]{0,50}(?![\s\S]{0,30}hierarchy|[\s\S]{0,30}inherit)/i,
      desc: 'Role checks may not respect hierarchy.',
      rec: 'Implement proper role hierarchy checking.' },
    { id: 'SOL2047', name: 'Session Key Scope', severity: 'high',
      regex: /session[\s\S]{0,30}key[\s\S]{0,50}(?:sign|execute)[\s\S]{0,30}(?![\s\S]{0,20}scope|[\s\S]{0,20}limit)/i,
      desc: 'Session keys without operation scope limits.',
      rec: 'Limit session key permissions to specific operations.' },
    { id: 'SOL2048', name: 'CPI Authority Escalation', severity: 'critical',
      regex: /invoke[\s\S]{0,50}signer_seeds[\s\S]{0,30}(?:any|arbitrary|user)/i,
      desc: 'CPI using arbitrary user-provided seeds.',
      rec: 'Validate signer seeds against expected values.' },
    { id: 'SOL2049', name: 'Token Metadata Authority', severity: 'high',
      regex: /metadata[\s\S]{0,30}(?:update|modify)[\s\S]{0,30}authority[\s\S]{0,30}(?![\s\S]{0,20}verify)/i,
      desc: 'Metadata update authority not verified.',
      rec: 'Verify metadata update authority before changes.' },
    { id: 'SOL2050', name: 'Collection Authority Spoof', severity: 'critical',
      regex: /collection[\s\S]{0,30}(?:verify|sign)[\s\S]{0,30}(?![\s\S]{0,20}authority|[\s\S]{0,20}creator)/i,
      desc: 'Collection verification without authority check.',
      rec: 'Verify collection authority signature.' },
    { id: 'SOL2051', name: 'Upgrade Authority Leak', severity: 'critical',
      regex: /upgrade[\s\S]{0,30}authority[\s\S]{0,50}(?:pubkey|key)[\s\S]{0,30}(?:set|assign|change)/i,
      desc: 'Program upgrade authority can be changed unsafely.',
      rec: 'Make upgrade authority immutable or use multi-sig.' },
    { id: 'SOL2052', name: 'Close Authority Missing', severity: 'high',
      regex: /close[\s\S]{0,30}account[\s\S]{0,50}(?![\s\S]{0,30}authority|[\s\S]{0,30}owner)/i,
      desc: 'Account closure without authority verification.',
      rec: 'Verify close authority before account closure.' },
    { id: 'SOL2053', name: 'Rent Payer Authority', severity: 'medium',
      regex: /rent[\s\S]{0,30}payer[\s\S]{0,50}(?![\s\S]{0,30}signer|[\s\S]{0,30}verify)/i,
      desc: 'Rent payer not verified as signer.',
      rec: 'Require rent payer signature.' },
    { id: 'SOL2054', name: 'Crank Permission', severity: 'medium',
      regex: /crank[\s\S]{0,30}(?:execute|call)[\s\S]{0,50}(?:anyone|permissionless)/i,
      desc: 'Permissionless cranking may enable extraction.',
      rec: 'Add incentives or restrictions for cranking.' },
    { id: 'SOL2055', name: 'Initializer Authority', severity: 'high',
      regex: /init[\s\S]{0,30}(?:authority|admin)[\s\S]{0,50}(?:caller|signer)[\s\S]{0,30}(?![\s\S]{0,20}hardcode)/i,
      desc: 'Initializer becomes authority by default.',
      rec: 'Separate initialization from authority assignment.' },

    // 2024-2025 Emerging Attack Vectors (SOL2056-SOL2070)
    { id: 'SOL2056', name: 'Blink Action Validation', severity: 'high',
      regex: /blink|action[\s\S]{0,30}(?:url|endpoint)[\s\S]{0,30}(?![\s\S]{0,20}verify|[\s\S]{0,20}whitelist)/i,
      desc: 'Blink action URLs not validated.',
      rec: 'Whitelist allowed blink action endpoints.' },
    { id: 'SOL2057', name: 'Compression Proof Spoofing', severity: 'critical',
      regex: /compression[\s\S]{0,30}proof[\s\S]{0,50}(?:verify|check)[\s\S]{0,30}(?![\s\S]{0,20}root)/i,
      desc: 'Compressed NFT proof verification incomplete.',
      rec: 'Verify proof against current merkle root.' },
    { id: 'SOL2058', name: 'Token-2022 Extension Abuse', severity: 'high',
      regex: /token[\s\S]{0,10}2022[\s\S]{0,30}extension[\s\S]{0,30}(?![\s\S]{0,20}verify|[\s\S]{0,20}check)/i,
      desc: 'Token-2022 extensions not properly validated.',
      rec: 'Validate extension states before operations.' },
    { id: 'SOL2059', name: 'Transfer Hook Reentrancy', severity: 'critical',
      regex: /transfer[\s\S]{0,30}hook[\s\S]{0,50}(?:invoke|call)[\s\S]{0,30}(?![\s\S]{0,20}guard|[\s\S]{0,20}lock)/i,
      desc: 'Transfer hooks may enable reentrancy.',
      rec: 'Add reentrancy guards for transfer hooks.' },
    { id: 'SOL2060', name: 'Confidential Transfer Leak', severity: 'high',
      regex: /confidential[\s\S]{0,30}transfer[\s\S]{0,50}(?:log|emit|print)/i,
      desc: 'Confidential transfer amounts may be leaked.',
      rec: 'Never log confidential transfer details.' },
    { id: 'SOL2061', name: 'Interest Bearing Manipulation', severity: 'high',
      regex: /interest[\s\S]{0,30}bearing[\s\S]{0,50}rate[\s\S]{0,30}(?:set|update)/i,
      desc: 'Interest bearing token rate can be manipulated.',
      rec: 'Add timelock for interest rate changes.' },
    { id: 'SOL2062', name: 'Permanent Delegate Abuse', severity: 'critical',
      regex: /permanent[\s\S]{0,30}delegate[\s\S]{0,50}(?![\s\S]{0,30}revoke|[\s\S]{0,30}remove)/i,
      desc: 'Permanent delegate cannot be revoked.',
      rec: 'Avoid permanent delegates or add revocation.' },
    { id: 'SOL2063', name: 'CPI Guard State', severity: 'high',
      regex: /cpi[\s\S]{0,30}guard[\s\S]{0,50}(?:enable|disable)[\s\S]{0,30}(?![\s\S]{0,20}verify)/i,
      desc: 'CPI guard state changes not verified.',
      rec: 'Verify CPI guard state before sensitive operations.' },
    { id: 'SOL2064', name: 'Memo Required Bypass', severity: 'medium',
      regex: /memo[\s\S]{0,30}required[\s\S]{0,50}(?:skip|bypass|ignore)/i,
      desc: 'Required memo can be bypassed.',
      rec: 'Enforce memo requirement at protocol level.' },
    { id: 'SOL2065', name: 'Non-Transferable Override', severity: 'high',
      regex: /non[\s\S]{0,5}transferable[\s\S]{0,50}(?:override|bypass|exception)/i,
      desc: 'Non-transferable tokens can be transferred.',
      rec: 'Remove override capabilities for non-transferable.' },
    { id: 'SOL2066', name: 'Default Account State Abuse', severity: 'medium',
      regex: /default[\s\S]{0,30}account[\s\S]{0,30}state[\s\S]{0,30}(?:frozen|initialized)/i,
      desc: 'Default account state can lock user funds.',
      rec: 'Clearly document default account state behavior.' },
    { id: 'SOL2067', name: 'Reallocate Without Check', severity: 'high',
      regex: /realloc[\s\S]{0,50}(?:size|space)[\s\S]{0,30}(?![\s\S]{0,20}max|[\s\S]{0,20}limit)/i,
      desc: 'Account reallocation without size limits.',
      rec: 'Enforce maximum account size limits.' },
    { id: 'SOL2068', name: 'Lookup Table Poison', severity: 'critical',
      regex: /lookup[\s\S]{0,30}table[\s\S]{0,50}(?:extend|add)[\s\S]{0,30}(?![\s\S]{0,20}verify)/i,
      desc: 'Address lookup tables can be poisoned.',
      rec: 'Verify lookup table authority and contents.' },
    { id: 'SOL2069', name: 'Durable Nonce Exploitation', severity: 'high',
      regex: /durable[\s\S]{0,30}nonce[\s\S]{0,50}(?:advance|consume)[\s\S]{0,30}(?![\s\S]{0,20}verify)/i,
      desc: 'Durable nonce state not properly verified.',
      rec: 'Verify nonce account state and authority.' },
    { id: 'SOL2070', name: 'Versioned Transaction Confusion', severity: 'medium',
      regex: /version[\s\S]{0,30}transaction[\s\S]{0,50}(?:legacy|v0)[\s\S]{0,30}(?![\s\S]{0,20}check)/i,
      desc: 'Transaction version handling may cause confusion.',
      rec: 'Explicitly handle both legacy and versioned transactions.' },
  ];

  for (const p of patterns) {
    const matches = content.matchAll(new RegExp(p.regex.source, p.regex.flags + 'g'));
    for (const match of matches) {
      const line = findLine(content, match.index || 0);
      findings.push({
        id: p.id,
        title: p.name,
        severity: p.severity,
        description: p.desc,
        location: { file: path, line },
        recommendation: p.rec,
        code: getSnippet(content, line),
      });
    }
  }

  return findings;
}

export const BATCH_53_PATTERN_COUNT = 70;
